apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unique
  name: unique
  labels:
    app: unique
spec:
  selector:
    matchLabels:
      app: unique
  template:
    metadata:
      labels:
        app: unique
        name: unique
    spec:
      containers:
        - name: unique
          image: unnagirirao/Unique/unique
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 5634
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        